# Generated by Django 5.2.3 on 2025-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcategory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
