# Generated by Django 5.2.3 on 2025-07-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceandmediacategory',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_categories', to='brdc.resourceandmediasection'),
        ),
    ]
