# Generated by Django 5.2.3 on 2025-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdc', '0002_alter_resourceandmediacategory_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcategory',
            name='intro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
