# Generated by Django 5.2.3 on 2025-07-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdc', '0003_aboutcategory_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceandmediacategory',
            name='about',
        ),
        migrations.AddField(
            model_name='resourceandmediacategory',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='brdc.resourceandmediasection'),
        ),
    ]
