# Generated by Django 5.2.3 on 2025-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brdc', '0006_team_is_adivisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
